### ISSUE TITLE
Does it work for flash on IOS?

### ISSUE THREAD

**Issue by catalinux** [TouchScript/TouchScript.as3#1]
Where can I see a flash demo for multitouch gestures?

**Comment by valyard** [comment]
Check out the demo app. It uses pan and rotate gestures together.

**Comment by catalinux** [comment]
Hi. Can you point me to the location of this app?

**Comment by valyard** [comment]
This one: https://github.com/InteractiveLab/TouchScript.as3/tree/master/Examples/TestProject

**Comment by acheson** [comment]
I have just wrapped a project in AIR 3.6 for desktop and it works great (Awesome work on your part!).

I am trying to run the same code on iOS (6 and 7) but only getting one touch point at a time; no scale or rotate gestures.  I have tried the TestProject with the same results.

Any suggestions???

**Comment by valyard** [comment]
Not sure.
Same touch input should work as far as I know.
If you are getting only one touch point it might mean that only mouse is used.

**Comment by acheson** [comment]
You are correct.  Only mouse is working.  

When I push to the iPad, everything seems like it is being initialized, constructors called, listeners added, etc, but only the mouse touches are firing.  I upgraded to AIR 3.9 to get DatagramSocket support, but still no luck.

**Comment by acheson** [comment]
I had to put it down and come back to figure it out...
I was using TuioInput which worked great for the touch screen but not for iOS.  As soon as I switched to WMTouchInput everything worked right away.

Cheers!
