### ISSUE TITLE
TouchScript between Unity scenes

### ISSUE THREAD

**Issue by Wintuco** [TouchScript/TouchScript.as3#2]
What is appropriate way of using TS between scene loads in Unity? Currently it works for me only once after first scene load, till next scene change/reload. This solution https://github.com/InteractiveLab/TouchScript/issues/27 didn't help me. The problem can be reproduced even in example scenes when triggering Application.LoadLevel by any touch gesture.

**Comment by valyard** [comment]
Happens with the latest develop branch too?

**Comment by Wintuco** [comment]
No, with dev branch works fine, thanks.
