### ISSUE TITLE
Documentation for AS3

### ISSUE THREAD

**Issue by Oesoto** [TouchScript/TouchScript.as3#4]
Where can I find a copy of the documentation for AS3?

I see a very good explanation of the library for Unity and I'd like to have something similar for AS3 so I can know with more detail how I can use this library

Thanks

**Comment by valyard** [comment]
Unfortunately only from examples (https://github.com/TouchScript/TouchScript.as3/tree/master/Examples). This library has been discontinued long time ago when I stopped developing with AS3.

**Comment by Oesoto** [comment]
Thank you @valyard I already took a look at the examples and they're working fine for me.

I'll try to understand how the library works as much as I can from those pieces of code

I think it's time to move away from AS3 to Unity :P

**Comment by valyard** [comment]
Join the Dark Side!
